sudo: required

services: docker

# Perform a shallow clone for speed. The default depth is 50.
# https://docs.travis-ci.com/user/customizing-the-build#Git-Clone-Depth
git:
  depth: 3

# Upgrade to the latest version of Docker
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

install: make image

script: docker run rlucioni/craigbot flake8

after_success: ./.travis/docker-push.sh
