sudo: required

services:
  - docker

before_install:
  - make image

script:
  - make quality

# https://docs.travis-ci.com/user/docker/#Pushing-a-Docker-Image-to-a-Registry
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    make push;
    fi
