language: python
python:
  - '3.6'

cache: pip

# Perform a shallow clone for speed. The default depth is 50.
# https://docs.travis-ci.com/user/customizing-the-build#Git-Clone-Depth
git:
  depth: 3

script: make lint
